name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1

      - name: Build Solution
        run: msbuild.exe CatHand4V.sln /nologo /p:platform="Any CPU" /p:configuration="Release"
